# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_member_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='memebers',
            new_name='members',
        ),
    ]
