# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20161025_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='year',
            new_name='added',
        ),
    ]
