# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20161025_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMCQChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('votes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackShortAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='students',
            field=models.ManyToManyField(blank=True, to='website.Member'),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='q_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('SHORT', 'Short answer type Question'), ('RATE', 'Rating Type Question')], default='RATE', max_length=5),
        ),
        migrations.AddField(
            model_name='feedbackratinganswer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbackshortanswer',
            name='q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FeedbackQuestion'),
        ),
        migrations.AddField(
            model_name='feedbackmcqchoice',
            name='q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FeedbackQuestion'),
        ),
    ]
