# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_feedback_added_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-added_on', '-deadline']},
        ),
    ]
