# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20161029_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-deadline']},
        ),
    ]
