# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20161029_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='token',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
