# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignments',
            new_name='Assignment',
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
