# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20161025_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='website.Member'),
        ),
    ]
