# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20161027_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=6),
        ),
    ]
