# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20161027_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
